name: CI/CD for Spring Boot & Angular

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build & Test Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and test backend
        working-directory: backend
        run: |
          mvn clean install
          mvn test

      - name: Store JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: backend/target/*.jar

  build-frontend:
    name: Build & Test Angular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies and build
        working-directory: frontend
        run: |
          npm install
          npm run test
          npm run build -- --configuration=production

      - name: Store Angular Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: angular-app
          path: frontend/dist/

  deploy:
    name: Deploy Backend & Frontend
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app
          path: backend/

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v3
        with:
          name: angular-app
          path: frontend/dist/
